// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: common/common.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommonService_GetUserInfo_FullMethodName = "/common.CommonService/GetUserInfo"
	CommonService_GetByCID_FullMethodName    = "/common.CommonService/GetByCID"
)

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonServiceClient interface {
	GetUserInfo(ctx context.Context, in *UserId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserInfo], error)
	GetByCID(ctx context.Context, in *FileCID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileResponse], error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) GetUserInfo(ctx context.Context, in *UserId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommonService_ServiceDesc.Streams[0], CommonService_GetUserInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserId, UserInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommonService_GetUserInfoClient = grpc.ServerStreamingClient[UserInfo]

func (c *commonServiceClient) GetByCID(ctx context.Context, in *FileCID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommonService_ServiceDesc.Streams[1], CommonService_GetByCID_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileCID, FileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommonService_GetByCIDClient = grpc.ServerStreamingClient[FileResponse]

// CommonServiceServer is the server API for CommonService service.
// All implementations must embed UnimplementedCommonServiceServer
// for forward compatibility.
type CommonServiceServer interface {
	GetUserInfo(*UserId, grpc.ServerStreamingServer[UserInfo]) error
	GetByCID(*FileCID, grpc.ServerStreamingServer[FileResponse]) error
	mustEmbedUnimplementedCommonServiceServer()
}

// UnimplementedCommonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonServiceServer struct{}

func (UnimplementedCommonServiceServer) GetUserInfo(*UserId, grpc.ServerStreamingServer[UserInfo]) error {
	return status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedCommonServiceServer) GetByCID(*FileCID, grpc.ServerStreamingServer[FileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetByCID not implemented")
}
func (UnimplementedCommonServiceServer) mustEmbedUnimplementedCommonServiceServer() {}
func (UnimplementedCommonServiceServer) testEmbeddedByValue()                       {}

// UnsafeCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServiceServer will
// result in compilation errors.
type UnsafeCommonServiceServer interface {
	mustEmbedUnimplementedCommonServiceServer()
}

func RegisterCommonServiceServer(s grpc.ServiceRegistrar, srv CommonServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommonService_ServiceDesc, srv)
}

func _CommonService_GetUserInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommonServiceServer).GetUserInfo(m, &grpc.GenericServerStream[UserId, UserInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommonService_GetUserInfoServer = grpc.ServerStreamingServer[UserInfo]

func _CommonService_GetByCID_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileCID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommonServiceServer).GetByCID(m, &grpc.GenericServerStream[FileCID, FileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommonService_GetByCIDServer = grpc.ServerStreamingServer[FileResponse]

// CommonService_ServiceDesc is the grpc.ServiceDesc for CommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserInfo",
			Handler:       _CommonService_GetUserInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetByCID",
			Handler:       _CommonService_GetByCID_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "common/common.proto",
}

const (
	UploadFileServiceStreaming_UploadFile_FullMethodName = "/common.UploadFileServiceStreaming/UploadFile"
)

// UploadFileServiceStreamingClient is the client API for UploadFileServiceStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadFileServiceStreamingClient interface {
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientRequest, UploadFileResponse], error)
}

type uploadFileServiceStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadFileServiceStreamingClient(cc grpc.ClientConnInterface) UploadFileServiceStreamingClient {
	return &uploadFileServiceStreamingClient{cc}
}

func (c *uploadFileServiceStreamingClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientRequest, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UploadFileServiceStreaming_ServiceDesc.Streams[0], UploadFileServiceStreaming_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientRequest, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UploadFileServiceStreaming_UploadFileClient = grpc.ClientStreamingClient[ClientRequest, UploadFileResponse]

// UploadFileServiceStreamingServer is the server API for UploadFileServiceStreaming service.
// All implementations must embed UnimplementedUploadFileServiceStreamingServer
// for forward compatibility.
type UploadFileServiceStreamingServer interface {
	UploadFile(grpc.ClientStreamingServer[ClientRequest, UploadFileResponse]) error
	mustEmbedUnimplementedUploadFileServiceStreamingServer()
}

// UnimplementedUploadFileServiceStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploadFileServiceStreamingServer struct{}

func (UnimplementedUploadFileServiceStreamingServer) UploadFile(grpc.ClientStreamingServer[ClientRequest, UploadFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedUploadFileServiceStreamingServer) mustEmbedUnimplementedUploadFileServiceStreamingServer() {
}
func (UnimplementedUploadFileServiceStreamingServer) testEmbeddedByValue() {}

// UnsafeUploadFileServiceStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadFileServiceStreamingServer will
// result in compilation errors.
type UnsafeUploadFileServiceStreamingServer interface {
	mustEmbedUnimplementedUploadFileServiceStreamingServer()
}

func RegisterUploadFileServiceStreamingServer(s grpc.ServiceRegistrar, srv UploadFileServiceStreamingServer) {
	// If the following call pancis, it indicates UnimplementedUploadFileServiceStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UploadFileServiceStreaming_ServiceDesc, srv)
}

func _UploadFileServiceStreaming_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadFileServiceStreamingServer).UploadFile(&grpc.GenericServerStream[ClientRequest, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UploadFileServiceStreaming_UploadFileServer = grpc.ClientStreamingServer[ClientRequest, UploadFileResponse]

// UploadFileServiceStreaming_ServiceDesc is the grpc.ServiceDesc for UploadFileServiceStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadFileServiceStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.UploadFileServiceStreaming",
	HandlerType: (*UploadFileServiceStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _UploadFileServiceStreaming_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "common/common.proto",
}
